### ISSUE TITLE
Field "id" not found after using the "Enhance" button

### ISSUE THREAD

**Issue by nextosai** [FMXExpress/Stable-Diffusion-Desktop-Client#1]
Congrats on this amazing app! I'm only having an issue when clicking on the "Enhance" button. When doing so, my Prompt (from the default one) changes to:

"portrait photo headshot by mucha, sharp focus, elegant, render, octane, detailed, award winning photography, masterpiece, rim lit cinematic lighting shot at night with 1 9 2 0 s studio composition and old vintageines cinema light rays from a distance in the background - w 8 3 4 6 7 5 mm picture is magic hour trending on artstation. behance hd crisp image b" . 

Then when clicking on the "Generate" button, I get an error: **"FDMemTable1: Field "id" not found"**

Thank You!

**Comment by FMXExpress** [comment]
I'll take a look. Could be throwing an error. It doesnt have much error handling if Replicate throws an error.
